### ISSUE TITLE
Installing docker updates on doc & whales sometimes kills the proxy

### ISSUE THREAD

**Issue by sarukuku** [bond-agency/nginx-le-proxy#2]
So the case is as stated in the issue title. I'm not sure why this happens. The container seems to just be stopped. If we add a restart policy to all containers that make the proxy system it might help with the situation. Here's how: https://docs.docker.com/compose/compose-file/#restart_policy

**Comment by roopemerikukka** [comment]
This should be solved in https://github.com/bond-agency/nginx-le-proxy/pull/3
